"""empty message

Revision ID: 166a4001188c
Revises: d320dfb61e67
Create Date: 2021-01-13 03:18:09.321332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166a4001188c'
down_revision = 'd320dfb61e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_data', sa.Column('tel', sa.String(), nullable=False))
    op.add_column('checkout_data', sa.Column('total_sum', sa.Integer(), nullable=False))
    op.add_column('checkout_data', sa.Column('town', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout_data', 'updated_on')
    op.drop_column('checkout_data', 'town')
    op.drop_column('checkout_data', 'total_sum')
    op.drop_column('checkout_data', 'tel')
    # ### end Alembic commands ###
