"""empty message

Revision ID: 1823f0eead36
Revises: 166a4001188c
Create Date: 2021-01-13 03:50:43.219902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1823f0eead36'
down_revision = '166a4001188c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_data', sa.Column('appartment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout_data', 'appartment')
    # ### end Alembic commands ###
