"""empty message

Revision ID: 7ffce441bfdc
Revises: 1823f0eead36
Create Date: 2021-02-06 18:47:28.204481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffce441bfdc'
down_revision = '1823f0eead36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('checkout_data', sa.Column('products_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout_data', 'products_id')
    op.drop_table('admin_data')
    # ### end Alembic commands ###
