"""empty message

Revision ID: 916f4c05550c
Revises: b2ad4a9d6163
Create Date: 2020-12-22 00:40:45.603703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916f4c05550c'
down_revision = 'b2ad4a9d6163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('title', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
