"""empty message

Revision ID: d320dfb61e67
Revises: 72c354cf66fb
Create Date: 2021-01-13 03:16:40.839378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd320dfb61e67'
down_revision = '72c354cf66fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_data', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('checkout_data', sa.Column('email', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('house_num', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('promocode', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('street', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('tel', sa.String(), nullable=False))
    op.add_column('checkout_data', sa.Column('total_sum', sa.Integer(), nullable=False))
    op.add_column('checkout_data', sa.Column('town', sa.String(), nullable=True))
    op.add_column('checkout_data', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout_data', 'updated_on')
    op.drop_column('checkout_data', 'town')
    op.drop_column('checkout_data', 'total_sum')
    op.drop_column('checkout_data', 'tel')
    op.drop_column('checkout_data', 'street')
    op.drop_column('checkout_data', 'promocode')
    op.drop_column('checkout_data', 'house_num')
    op.drop_column('checkout_data', 'email')
    op.drop_column('checkout_data', 'created_on')
    # ### end Alembic commands ###
